[package]
name = "mercs2_ui"
version = "1.1.1"
edition = "2021"
description = "Mercenaries 2 reimpl — GUI/HUD/Scaleform + input extensions."
readme = "README.md"
license.workspace = true
repository.workspace = true

[dependencies]
mercs2_core = { workspace = true }
mercs2_formats = { workspace = true }
