//! The engine's native ECS component-class registry — the *typed* half of the live bridge's phase 4.
//!
//! Where [`crate::essapi`] catalogues the Lua **callables** (`Ess.*`, `Pg.*`), this catalogues the
//! ~220 engine **component classes** the reflection system registers (`docs/mercs2-ecs/`, cracked
//! from the EXE): `RuntimeHealth`, `StateMachine`, `Explosive`, `AiPatrol`, … Each is a real ECS
//! type with a pool and a `CopyFromStream` deserializer, grouped into nine families.
//!
//! It is loaded from a bundled TSV (`workshop_data/ecs_registry.tsv`, generated by
//! `scripts/regen-ess-api.sh` from the vendored `docs/mercs2-ecs/_manifests/`, one row per class:
//! `family<TAB>name<TAB>registrar-global<TAB>descriptor-vtable`). It gives the console a typed
//! vocabulary to name what a live entity *is made of* — the read side of phase 4. The live reads that
//! the game actually serves today (health and destruction state, via `GetHealth`/`GetState`) are in
//! [`mercs2_destruction::live`]; a generic per-component read waits on Ess growing a component-read
//! verb (Plan 03 phase 4, open — extends Wally's repo).

use std::path::Path;

/// One registered engine component class.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EcsClass {
    /// The class name, e.g. `RuntimeHealth`.
    pub name: String,
    /// Which of the nine families it belongs to, e.g. `gameplay_state_health_mission`.
    pub family: String,
    /// The registrar global (`0x017b…`) — the descriptor's home in the EXE. Kept for cross-reference
    /// with the Ghidra decompilation, not shown in the console.
    pub global: String,
    /// The per-component descriptor vtable (`0x00bc…`).
    pub vtable: String,
}

impl EcsClass {
    /// The reference-list label: `RuntimeHealth  [gameplay_state_health_mission]`.
    pub fn label(&self) -> String {
        format!("{}  [{}]", self.name, self.family)
    }
}

/// The loaded component registry, with a lowercased search key per class computed once.
#[derive(Debug, Default, Clone)]
pub struct EcsRegistry {
    pub classes: Vec<EcsClass>,
    keys: Vec<String>,
}

impl EcsRegistry {
    /// Load the bundled `ecs_registry.tsv` from a `workshop_data/` directory. A missing or malformed
    /// file is not fatal — the console degrades to "no component registry" rather than refusing to
    /// open, exactly like [`crate::essapi::ApiIndex::load`].
    pub fn load(data_home: &Path) -> EcsRegistry {
        let mut reg = EcsRegistry::default();
        let Ok(text) = std::fs::read_to_string(data_home.join("ecs_registry.tsv")) else {
            return reg;
        };
        for line in text.lines() {
            let mut cols = line.split('\t');
            let (Some(family), Some(name)) = (cols.next(), cols.next()) else { continue };
            if name.is_empty() {
                continue;
            }
            reg.classes.push(EcsClass {
                name: name.to_string(),
                family: family.to_string(),
                global: cols.next().unwrap_or_default().to_string(),
                vtable: cols.next().unwrap_or_default().to_string(),
            });
        }
        reg.classes.sort_by(|a, b| a.name.cmp(&b.name));
        reg.classes.dedup_by(|a, b| a.name == b.name);
        reg.keys = reg
            .classes
            .iter()
            .map(|c| format!("{} {}", c.name, c.family).to_lowercase())
            .collect();
        reg
    }

    /// Classes whose name or family contains every whitespace-separated term of `query`
    /// (case-insensitive), capped at `limit`. An empty query returns nothing, like the API search —
    /// the reference shows only when the author is looking.
    pub fn search(&self, query: &str, limit: usize) -> Vec<&EcsClass> {
        let terms: Vec<String> = query.split_whitespace().map(|t| t.to_lowercase()).collect();
        if terms.is_empty() {
            return Vec::new();
        }
        let mut hits: Vec<&EcsClass> = self
            .classes
            .iter()
            .zip(&self.keys)
            .filter(|(_, key)| terms.iter().all(|t| key.contains(t)))
            .map(|(c, _)| c)
            .collect();
        // Shorter names (closer matches) first, then alphabetical — the same shape as the API search.
        hits.sort_by(|a, b| a.name.len().cmp(&b.name.len()).then_with(|| a.name.cmp(&b.name)));
        hits.truncate(limit);
        hits
    }

    /// One class by exact name (case-insensitive).
    pub fn class(&self, name: &str) -> Option<&EcsClass> {
        self.classes.iter().find(|c| c.name.eq_ignore_ascii_case(name))
    }

    /// The families present, each with its class count — for a grouped reference view.
    pub fn families(&self) -> Vec<(String, usize)> {
        let mut counts: std::collections::BTreeMap<&str, usize> = std::collections::BTreeMap::new();
        for c in &self.classes {
            *counts.entry(c.family.as_str()).or_default() += 1;
        }
        counts.into_iter().map(|(f, n)| (f.to_string(), n)).collect()
    }

    pub fn is_empty(&self) -> bool {
        self.classes.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn reg() -> EcsRegistry {
        let mut r = EcsRegistry {
            classes: vec![
                EcsClass { name: "RuntimeHealth".into(), family: "gameplay_state_health_mission".into(), global: "0x1".into(), vtable: "0x2".into() },
                EcsClass { name: "StateMachine".into(), family: "gameplay_state_health_mission".into(), global: "0x3".into(), vtable: "0x4".into() },
                EcsClass { name: "AiPatrol".into(), family: "ai_perception_population".into(), global: "0x5".into(), vtable: "0x6".into() },
            ],
            keys: vec![],
        };
        r.keys = r.classes.iter().map(|c| format!("{} {}", c.name, c.family).to_lowercase()).collect();
        r
    }

    #[test]
    fn search_matches_name_and_family_and_needs_every_term() {
        let r = reg();
        // A distinct name fragment narrows to one. ("health" alone would ALSO match StateMachine,
        // whose family `gameplay_state_health_mission` contains the word — the search is over name AND
        // family, by design, so the discriminating term is the unique part of the name.)
        assert_eq!(r.search("runtime", 10).len(), 1);
        assert_eq!(r.search("runtime", 10)[0].name, "RuntimeHealth");
        assert_eq!(r.search("machine", 10).len(), 1);
        assert_eq!(r.search("machine", 10)[0].name, "StateMachine");
        // Every term must match: adding the family word keeps the same single hit.
        assert_eq!(r.search("machine gameplay", 10).len(), 1);
        // The shared family word matches both classes in that family.
        assert_eq!(r.search("gameplay", 10).len(), 2);
        assert!(r.search("", 10).is_empty(), "an empty query shows nothing");
        assert_eq!(r.class("aipatrol").unwrap().family, "ai_perception_population");
    }

    #[test]
    fn families_count_the_classes() {
        let fams = reg().families();
        assert!(fams.iter().any(|(f, n)| f == "gameplay_state_health_mission" && *n == 2));
        assert!(fams.iter().any(|(f, n)| f == "ai_perception_population" && *n == 1));
    }

    /// ★ THE SEAM (companion to the Ess one). The bundled `ecs_registry.tsv` must parse and carry the
    /// ~220 classes with their families — a regeneration that drops or renames the registry fails here
    /// rather than leaving the console's component reference silently empty.
    #[test]
    fn the_bundled_registry_parses_and_carries_the_classes() {
        let home = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../workshop_data");
        if !home.join("ecs_registry.tsv").is_file() {
            eprintln!("SKIPPING: no bundled ecs_registry.tsv (run scripts/regen-ess-api.sh)");
            return;
        }
        let r = EcsRegistry::load(&home);
        assert!(!r.is_empty(), "the bundled registry parsed to zero classes — the seam is broken");
        // The count the doc set states: 232 registered (220 gameplay + 12 render/pipeline).
        assert!(
            r.classes.len() > 210,
            "expected ~232 ECS classes, got {} — did the manifest partitions change?",
            r.classes.len()
        );
        // The destruction-relevant classes this project reasons about must be present and correctly
        // filed — these are what the live reads (health, state) touch.
        for name in ["RuntimeHealth", "StateMachine", "Health", "Explosive"] {
            assert!(r.class(name).is_some(), "the bundled registry lost {name}");
        }
        assert_eq!(
            r.class("RuntimeHealth").unwrap().family,
            "gameplay_state_health_mission",
            "RuntimeHealth is filed in the wrong family — manifest drift"
        );
        // All nine families are present.
        assert_eq!(r.families().len(), 9, "expected nine ECS families, got {}", r.families().len());
        eprintln!(
            "ecs registry: {} classes across {} families",
            r.classes.len(),
            r.families().len()
        );
    }
}
