//! The Ess / engine API reference — what the live console autocompletes against.
//!
//! Wally's `mercs2-lua-essentials` is the library a modder actually writes in the console (`Ess.*`),
//! sitting on the raw engine natives (`Pg.*`, `Mrx*`). Two manifests, both bundled in `workshop_data/`
//! (regenerated by `scripts/regen-ess-api.sh`, verified by `tests/ess_seam.rs`):
//!
//! - `ess_api.json` — every `Ess.NS.func(...)` DEFINED in his committed `src/*.lua` (his own
//!   `api/ess.json` is generated into a gitignored `dist/`, so we derive an equivalent from source).
//! - `ess_natives.json` — his committed catalogue of the raw engine surface.
//!
//! This module loads them into one flat, searchable index. It is the console's reference so a modder
//! does not have to keep a browser tab of his docs open to remember whether it is `Object.health` or
//! `Object.getHealth`.

use std::path::Path;

/// One callable the console can offer — an Ess wrapper or a raw engine native.
#[derive(Debug, Clone)]
pub struct ApiEntry {
    /// Fully-qualified call, e.g. `Ess.Object.health` or `Pg.Spawn`.
    pub name: String,
    /// The namespace segment (`Object`, `Pg`, …) — for grouping.
    pub ns: String,
    /// The parameter list as source, e.g. `(uGuid)`. Empty for natives with no recorded signature.
    pub sig: String,
    /// `true` for an `Ess.*` wrapper, `false` for a raw engine native.
    pub ess: bool,
}

/// The loaded reference: every entry, plus a lowercased search key computed once.
#[derive(Debug, Default, Clone)]
pub struct ApiIndex {
    pub entries: Vec<ApiEntry>,
    keys: Vec<String>,
}

impl ApiIndex {
    /// Load both manifests from a `workshop_data/` directory. Missing files are not fatal — the
    /// console degrades to "no reference loaded" rather than refusing to open.
    pub fn load(data_home: &Path) -> ApiIndex {
        let mut idx = ApiIndex::default();
        idx.load_ess(&data_home.join("ess_api.json"));
        idx.load_natives(&data_home.join("ess_natives.json"));
        idx.entries.sort_by(|a, b| a.name.cmp(&b.name));
        idx.entries.dedup_by(|a, b| a.name == b.name);
        idx.keys = idx.entries.iter().map(|e| e.name.to_lowercase()).collect();
        idx
    }

    fn load_ess(&mut self, path: &Path) {
        let Ok(text) = std::fs::read_to_string(path) else { return };
        let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) else { return };
        let Some(fns) = v.get("functions").and_then(|f| f.as_array()) else { return };
        for f in fns {
            let name = f.get("name").and_then(|s| s.as_str()).unwrap_or_default();
            if name.is_empty() {
                continue;
            }
            self.entries.push(ApiEntry {
                name: name.to_string(),
                ns: f.get("ns").and_then(|s| s.as_str()).unwrap_or_default().to_string(),
                sig: f.get("sig").and_then(|s| s.as_str()).unwrap_or("()").to_string(),
                ess: true,
            });
        }
    }

    /// His `natives.json` is `{ "aliases": {...}, "<Namespace>": { "<func>": ... } }` (plus the
    /// alias map). We take the qualified `Namespace.func` names — enough for autocomplete; the
    /// per-native detail lives in his docs.
    fn load_natives(&mut self, path: &Path) {
        let Ok(text) = std::fs::read_to_string(path) else { return };
        let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) else { return };
        let Some(obj) = v.as_object() else { return };
        for (ns, body) in obj {
            if ns == "aliases" {
                // Aliases are `alias -> canonical`; surface the alias name so a modder who types the
                // shorter form still finds it.
                if let Some(map) = body.as_object() {
                    for alias in map.keys() {
                        self.push_native(alias);
                    }
                }
                continue;
            }
            match body {
                serde_json::Value::Object(fns) => {
                    for func in fns.keys() {
                        self.push_native(&format!("{ns}.{func}"));
                    }
                }
                // A bare namespace with no sub-table: still worth offering the name.
                _ => self.push_native(ns),
            }
        }
    }

    fn push_native(&mut self, name: &str) {
        if name.is_empty() {
            return;
        }
        let ns = name.split('.').next().unwrap_or(name).to_string();
        self.entries.push(ApiEntry {
            name: name.to_string(),
            ns,
            sig: String::new(),
            ess: false,
        });
    }

    /// Entries whose name contains every whitespace-separated term of `query` (case-insensitive),
    /// capped at `limit`. An empty query returns nothing — the console shows the reference only when
    /// the author is looking for something. Ess wrappers rank before raw natives.
    pub fn search(&self, query: &str, limit: usize) -> Vec<&ApiEntry> {
        let terms: Vec<String> = query.split_whitespace().map(|t| t.to_lowercase()).collect();
        if terms.is_empty() {
            return Vec::new();
        }
        let mut hits: Vec<&ApiEntry> = self
            .entries
            .iter()
            .zip(&self.keys)
            .filter(|(_, key)| terms.iter().all(|t| key.contains(t)))
            .map(|(e, _)| e)
            .collect();
        // Ess wrappers first, then shorter names (closer matches), then alphabetical.
        hits.sort_by(|a, b| {
            b.ess
                .cmp(&a.ess)
                .then_with(|| a.name.len().cmp(&b.name.len()))
                .then_with(|| a.name.cmp(&b.name))
        });
        hits.truncate(limit);
        hits
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn search_ranks_ess_wrappers_first_and_matches_all_terms() {
        let idx = ApiIndex {
            entries: vec![
                ApiEntry { name: "Ess.Object.health".into(), ns: "Object".into(), sig: "(uGuid)".into(), ess: true },
                ApiEntry { name: "Object.GetHealth".into(), ns: "Object".into(), sig: String::new(), ess: false },
                ApiEntry { name: "Ess.Object.setPos".into(), ns: "Object".into(), sig: "(g,x,y,z)".into(), ess: true },
            ],
            keys: vec!["ess.object.health".into(), "object.gethealth".into(), "ess.object.setpos".into()],
        };
        let hits = idx.search("health", 10);
        assert_eq!(hits.len(), 2);
        assert_eq!(hits[0].name, "Ess.Object.health", "an Ess wrapper ranks before the raw native");
        // Multi-term: every term must match.
        assert_eq!(idx.search("object pos", 10).len(), 1);
        assert!(idx.search("", 10).is_empty(), "an empty query shows nothing");
    }

    /// ★ THE SEAM. The bundled manifests (`workshop_data/ess_api.json`, `ess_natives.json`) must
    /// still parse and still carry the surface the console assumes. This is what catches a drift in
    /// Wally's library — if a regeneration renames or drops these, the console's reference rots
    /// silently otherwise. Regenerate with `scripts/regen-ess-api.sh` when it fails on a real change.
    #[test]
    fn the_bundled_ess_manifest_parses_and_carries_the_expected_api() {
        let home = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../workshop_data");
        if !home.join("ess_api.json").is_file() {
            eprintln!("SKIPPING: no bundled ess_api.json (run scripts/regen-ess-api.sh)");
            return;
        }
        let idx = ApiIndex::load(&home);
        assert!(!idx.is_empty(), "the bundled manifest parsed to zero entries — the seam is broken");

        // Ess wrappers a modder relies on, and that this crate names elsewhere (the destruction and
        // name-resolution surface we compared against). A rename upstream fails HERE.
        for needle in ["Ess.Object.health", "Ess.Object.damage", "Ess.Object.kill", "Ess.Probe.nearby"] {
            assert!(
                idx.entries.iter().any(|e| e.name == needle),
                "the bundled Ess API no longer defines {needle} — regenerate the manifest and \
                 re-check the console/comparison that assumed it"
            );
        }
        // Both sides are present: Ess wrappers AND raw engine natives.
        assert!(idx.entries.iter().any(|e| e.ess), "no Ess wrappers loaded");
        assert!(idx.entries.iter().any(|e| !e.ess), "no engine natives loaded");
        // Search works against the real data.
        assert!(
            idx.search("health", 8).iter().any(|e| e.name == "Ess.Object.health"),
            "search over the real manifest did not find Ess.Object.health"
        );
        eprintln!(
            "ess seam: {} entries ({} Ess, {} native)",
            idx.entries.len(),
            idx.entries.iter().filter(|e| e.ess).count(),
            idx.entries.iter().filter(|e| !e.ess).count(),
        );
    }
}
