//! The Ess / engine API reference — what the live console autocompletes against.
//!
//! Wally's `mercs2-lua-essentials` is the library a modder actually writes in the console (`Ess.*`),
//! sitting on the raw engine natives (`Pg.*`, `Mrx*`). Two manifests, both bundled in `workshop_data/`
//! (regenerated by `scripts/regen-ess-api.sh`, verified by `tests/ess_seam.rs`):
//!
//! - `ess_api.json` — Wally's own generated manifest, taken verbatim from his release zip's
//!   `api/ess.json` (720 functions with tier / params / returns / description / source line). His
//!   repo generates it into a gitignored `dist/`, but the **release** ships it — so we bundle his
//!   authoritative file rather than deriving one.
//! - `ess_natives.json` — his committed catalogue of the raw engine surface.
//!
//! This module loads them into one flat, searchable index. It is the console's reference so a modder
//! does not have to keep a browser tab of his docs open to remember whether it is `Object.health` or
//! `Object.getHealth`.

use std::path::Path;

/// One callable the console can offer — an Ess wrapper or a raw engine native.
#[derive(Debug, Clone)]
pub struct ApiEntry {
    /// Fully-qualified call, e.g. `Ess.Object.health` or `Pg.Spawn`.
    pub name: String,
    /// The namespace segment (`Object`, `Pg`, …) — for grouping.
    pub ns: String,
    /// The parameter list as source, e.g. `(uGuid)`. Empty for natives with no recorded signature.
    pub sig: String,
    /// The Ess tier — `"easy"` / `"core"` / `"raw"` — or empty for a native. Guides the modder to
    /// the guardrailed presets first.
    pub tier: String,
    /// What it returns, when the manifest records it (e.g. `"ok"`, `"x,y,z | nil"`).
    pub returns: String,
    /// One-line description — the node catalogue's friendlier `desc_short` where it exists, else the
    /// manifest's terse `description`.
    pub doc: String,
    /// A human title from the visual-editor node catalogue (`nodes.json`), e.g. "AI Orders: Command".
    /// Empty when this call is not a graph node (most natives, a few internal wrappers).
    pub title: String,
    /// `true` for an `Ess.*` wrapper, `false` for a raw engine native.
    pub ess: bool,
}

impl ApiEntry {
    /// The one-line label for the reference list: `Ess.Object.health(uGuid) -> n  [core]`.
    pub fn label(&self) -> String {
        let mut s = format!("{}{}", self.name, self.sig);
        if !self.returns.is_empty() {
            s.push_str(&format!(" -> {}", self.returns));
        }
        s
    }
}

/// The loaded reference: every entry, plus a lowercased search key computed once.
#[derive(Debug, Default, Clone)]
pub struct ApiIndex {
    pub entries: Vec<ApiEntry>,
    keys: Vec<String>,
}

impl ApiIndex {
    /// Load both manifests from a `workshop_data/` directory. Missing files are not fatal — the
    /// console degrades to "no reference loaded" rather than refusing to open.
    pub fn load(data_home: &Path) -> ApiIndex {
        let mut idx = ApiIndex::default();
        idx.load_ess(&data_home.join("ess_api.json"));
        idx.load_natives(&data_home.join("ess_natives.json"));
        idx.entries.sort_by(|a, b| a.name.cmp(&b.name));
        idx.entries.dedup_by(|a, b| a.name == b.name);
        // Merge the visual-editor node catalogue's friendlier titles/prose over the terse manifest
        // descriptions, matched by `call`. This is prose enrichment, not new callables — it must run
        // after the entries exist and does not add any.
        idx.merge_nodes(&data_home.join("ess_nodes.json"));
        idx.keys = idx.entries.iter().map(|e| e.name.to_lowercase()).collect();
        idx
    }

    /// Overlay `nodes.json`'s `{call, title, desc_short, desc}` onto matching entries. `desc_short`
    /// (a complete sentence) replaces the manifest's often-fragmentary `description`; the title is
    /// added for a friendlier label. Nodes with no matching entry are ignored — this never invents a
    /// callable.
    fn merge_nodes(&mut self, path: &Path) {
        let Ok(text) = std::fs::read_to_string(path) else { return };
        let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) else { return };
        let Some(nodes) = v.get("nodes").and_then(|n| n.as_array()) else { return };
        let mut by_call: std::collections::HashMap<&str, (&str, &str)> = std::collections::HashMap::new();
        for n in nodes {
            let Some(call) = n.get("call").and_then(|s| s.as_str()) else { continue };
            let title = n.get("title").and_then(|s| s.as_str()).unwrap_or_default();
            // Prefer the concise-but-complete `desc_short`; fall back to the full `desc`.
            let desc = n
                .get("desc_short")
                .and_then(|s| s.as_str())
                .filter(|s| !s.is_empty())
                .or_else(|| n.get("desc").and_then(|s| s.as_str()))
                .unwrap_or_default();
            by_call.insert(call, (title, desc));
        }
        for e in &mut self.entries {
            if let Some((title, desc)) = by_call.get(e.name.as_str()) {
                if !title.is_empty() {
                    e.title = (*title).to_string();
                }
                if !desc.is_empty() {
                    e.doc = (*desc).to_string();
                }
            }
        }
    }

    /// Wally's `api/ess.json`: `{ "functions": { "Ess.NS.func": {namespace, tier, params[], returns,
    /// description, …}, … }, … }`. The key is the fully-qualified name; the params list becomes the
    /// `(a, b, c)` signature.
    fn load_ess(&mut self, path: &Path) {
        let Ok(text) = std::fs::read_to_string(path) else { return };
        let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) else { return };
        let Some(fns) = v.get("functions").and_then(|f| f.as_object()) else { return };
        for (name, f) in fns {
            if name.is_empty() {
                continue;
            }
            let params: Vec<&str> = f
                .get("params")
                .and_then(|p| p.as_array())
                .map(|a| a.iter().filter_map(|x| x.as_str()).collect())
                .unwrap_or_default();
            // `ns` is the last segment of the manifest's `namespace` (`Ess.Object` -> `Object`).
            let ns = f
                .get("namespace")
                .and_then(|s| s.as_str())
                .and_then(|s| s.rsplit('.').next())
                .unwrap_or_else(|| name.split('.').nth(1).unwrap_or(""))
                .to_string();
            self.entries.push(ApiEntry {
                name: name.clone(),
                ns,
                sig: format!("({})", params.join(", ")),
                tier: f.get("tier").and_then(|s| s.as_str()).unwrap_or_default().to_string(),
                returns: f.get("returns").and_then(|s| s.as_str()).unwrap_or_default().to_string(),
                doc: f.get("description").and_then(|s| s.as_str()).unwrap_or_default().to_string(),
                title: String::new(),
                ess: true,
            });
        }
    }

    /// His `natives.json` is `{ "aliases": {...}, "<Namespace>": { "<func>": ... } }` (plus the
    /// alias map). We take the qualified `Namespace.func` names — enough for autocomplete; the
    /// per-native detail lives in his docs.
    fn load_natives(&mut self, path: &Path) {
        let Ok(text) = std::fs::read_to_string(path) else { return };
        let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) else { return };
        let Some(obj) = v.as_object() else { return };
        for (ns, body) in obj {
            if ns == "aliases" {
                // Aliases are `alias -> canonical`; surface the alias name so a modder who types the
                // shorter form still finds it.
                if let Some(map) = body.as_object() {
                    for alias in map.keys() {
                        self.push_native(alias);
                    }
                }
                continue;
            }
            match body {
                serde_json::Value::Object(fns) => {
                    for func in fns.keys() {
                        self.push_native(&format!("{ns}.{func}"));
                    }
                }
                // A bare namespace with no sub-table: still worth offering the name.
                _ => self.push_native(ns),
            }
        }
    }

    fn push_native(&mut self, name: &str) {
        if name.is_empty() {
            return;
        }
        let ns = name.split('.').next().unwrap_or(name).to_string();
        self.entries.push(ApiEntry {
            name: name.to_string(),
            ns,
            sig: String::new(),
            tier: String::new(),
            returns: String::new(),
            doc: String::new(),
            title: String::new(),
            ess: false,
        });
    }

    /// Entries whose name contains every whitespace-separated term of `query` (case-insensitive),
    /// capped at `limit`. An empty query returns nothing — the console shows the reference only when
    /// the author is looking for something. Ess wrappers rank before raw natives.
    pub fn search(&self, query: &str, limit: usize) -> Vec<&ApiEntry> {
        let terms: Vec<String> = query.split_whitespace().map(|t| t.to_lowercase()).collect();
        if terms.is_empty() {
            return Vec::new();
        }
        let mut hits: Vec<&ApiEntry> = self
            .entries
            .iter()
            .zip(&self.keys)
            .filter(|(_, key)| terms.iter().all(|t| key.contains(t)))
            .map(|(e, _)| e)
            .collect();
        // Ess wrappers first, then shorter names (closer matches), then alphabetical.
        hits.sort_by(|a, b| {
            b.ess
                .cmp(&a.ess)
                .then_with(|| a.name.len().cmp(&b.name.len()))
                .then_with(|| a.name.cmp(&b.name))
        });
        hits.truncate(limit);
        hits
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn search_ranks_ess_wrappers_first_and_matches_all_terms() {
        let e = |name: &str, ess: bool| ApiEntry {
            name: name.into(),
            ns: "Object".into(),
            sig: String::new(),
            tier: if ess { "core".into() } else { String::new() },
            returns: String::new(),
            doc: String::new(),
            title: String::new(),
            ess,
        };
        let idx = ApiIndex {
            entries: vec![e("Ess.Object.health", true), e("Object.GetHealth", false), e("Ess.Object.setPos", true)],
            keys: vec!["ess.object.health".into(), "object.gethealth".into(), "ess.object.setpos".into()],
        };
        let hits = idx.search("health", 10);
        assert_eq!(hits.len(), 2);
        assert_eq!(hits[0].name, "Ess.Object.health", "an Ess wrapper ranks before the raw native");
        // Multi-term: every term must match.
        assert_eq!(idx.search("object pos", 10).len(), 1);
        assert!(idx.search("", 10).is_empty(), "an empty query shows nothing");
    }

    /// ★ THE SEAM. The bundled manifests (`workshop_data/ess_api.json`, `ess_natives.json`) must
    /// still parse and still carry the surface the console assumes. This is what catches a drift in
    /// Wally's library — if a regeneration renames or drops these, the console's reference rots
    /// silently otherwise. Regenerate with `scripts/regen-ess-api.sh` when it fails on a real change.
    #[test]
    fn the_bundled_ess_manifest_parses_and_carries_the_expected_api() {
        let home = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../workshop_data");
        if !home.join("ess_api.json").is_file() {
            eprintln!("SKIPPING: no bundled ess_api.json (run scripts/regen-ess-api.sh)");
            return;
        }
        let idx = ApiIndex::load(&home);
        assert!(!idx.is_empty(), "the bundled manifest parsed to zero entries — the seam is broken");

        // Ess wrappers a modder relies on, and that this crate names elsewhere (the destruction and
        // name-resolution surface we compared against). A rename upstream fails HERE.
        for needle in ["Ess.Object.health", "Ess.Object.damage", "Ess.Object.kill", "Ess.Probe.nearby"] {
            assert!(
                idx.entries.iter().any(|e| e.name == needle),
                "the bundled Ess API no longer defines {needle} — regenerate the manifest and \
                 re-check the console/comparison that assumed it"
            );
        }
        // Both sides are present: Ess wrappers AND raw engine natives.
        assert!(idx.entries.iter().any(|e| e.ess), "no Ess wrappers loaded");
        assert!(idx.entries.iter().any(|e| !e.ess), "no engine natives loaded");
        // His real schema carries tiers and signatures — the metadata the console shows. If a future
        // manifest drops these, the reference goes bare and this catches it.
        let health = idx.entries.iter().find(|e| e.name == "Ess.Object.health").unwrap();
        assert!(!health.tier.is_empty(), "Ess.Object.health lost its tier — schema drift");
        assert!(health.sig.contains("uGuid") || health.sig != "()", "Ess.Object.health lost its params");
        assert!(
            idx.entries.iter().any(|e| e.ess && e.tier == "easy"),
            "no easy-tier wrappers — the tier field is not being read"
        );
        // Search works against the real data.
        assert!(
            idx.search("health", 8).iter().any(|e| e.name == "Ess.Object.health"),
            "search over the real manifest did not find Ess.Object.health"
        );
        // The node catalogue folded in: many wrappers gained a friendly title + a fuller sentence.
        let with_title = idx.entries.iter().filter(|e| !e.title.is_empty()).count();
        assert!(
            with_title > 400,
            "expected the node catalogue (~649 nodes) to enrich most wrappers, got {with_title} \
             titled — is ess_nodes.json bundled / did its schema drift?"
        );
        let cmd = idx.entries.iter().find(|e| e.name == "Ess.AIOrders.command").unwrap();
        assert_eq!(cmd.title, "AI Orders: Command", "node title did not merge onto its call");
        assert!(cmd.doc.len() > 20, "node desc did not replace the terse manifest description");
        eprintln!(
            "ess seam: {} entries ({} Ess, {} native); tiers e/c/r = {}/{}/{}; {} node-titled",
            idx.entries.len(),
            idx.entries.iter().filter(|e| e.ess).count(),
            idx.entries.iter().filter(|e| !e.ess).count(),
            idx.entries.iter().filter(|e| e.tier == "easy").count(),
            idx.entries.iter().filter(|e| e.tier == "core").count(),
            idx.entries.iter().filter(|e| e.tier == "raw").count(),
            with_title,
        );
    }
}
